### ISSUE TITLE
Submission Form Selector Hidden on Small Screens

### ISSUE THREAD

**Issue by kjohnson** [wpninjas/ninja-forms#2296]
On the submission screen, the form selector is being hidden by WordPress Admin Styles.

```css
@media screen and (max-width: 782px)
.form-wrap>p, .tablenav .view-switch, .tablenav.top .actions, .tablenav.top .displaying-num, .tablenav.top .tablenav-pages.one-page {
    display: none;
}
```
