### ISSUE TITLE
IE 11 does not support CSS 'clear: initial;'

### ISSUE THREAD

**Issue by amt925** [wpninjas/ninja-forms#2529]
IE 11 does not support the value `initial` for the `clear` property.

SCSS reference here: https://github.com/wpninjas/ninja-forms/blob/master/assets/scss/front-end/st-defaults.scss#L260

```scss
.five-sixths,
    .four-sixths,
    .one-fourth,
    .one-half,
    .one-sixth,
    .one-third,
    .three-fourths,
    .three-sixths,
    .two-fourths,
    .two-sixths,
    .two-thirds {
        clear: initial;
        float: left;
        margin-left: 2.564102564102564%;
        .inside {
            padding: 20px;
        }
        &::after {
            clear: both;
            content: "";
            display: block;
        }
    }
```

See here: https://developer.mozilla.org/en-US/docs/Web/CSS/clear and here: http://caniuse.com/#feat=css-initial-value for documentation.

This could be set to `inherit` or `none` since the 'initial' value is `none` by default.

```scss
.five-sixths,
    .four-sixths,
    .one-fourth,
    .one-half,
    .one-sixth,
    .one-third,
    .three-fourths,
    .three-sixths,
    .two-fourths,
    .two-sixths,
    .two-thirds {
        clear: inherit;
        float: left;
        margin-left: 2.564102564102564%;
        .inside {
            padding: 20px;
        }
        &::after {
            clear: both;
            content: "";
            display: block;
        }
    }
```
