### ISSUE TITLE
[Bug] Padding below honeypot

### ISSUE THREAD

**Issue by lonix1** [wpninjas/ninja-forms#3685]
Related to https://github.com/wpninjas/ninja-forms/issues/1338

Below the honeypot there is extra padding.
It has this:
````css
.nf-form-hp {
    position: absolute;
    visibility: hidden;
}
````

But it's still taking up space.

Surely it's better to use `display:none`? A bot ignores styles anyway.
