### ISSUE TITLE
[Bug] Telephone field does not get correct class after validation 

### ISSUE THREAD

**Issue by lonix1** [wpninjas/ninja-forms#3686]
When a form contains a field that passes validation, the following shows a green border:

````css
.nf-pass .ninja-forms-field { color: green !important; }
````

But this does not apply to telephone fields, because the `.nf-pass` class is not set on its container.
